### PR TITLE
Upgrade tui to 0.12.x

### PR DESCRIPTION
**Pull request by alexmaco**
Changes tested on linux. The apparent semantic changes to the code are only there to produce the same output after the `tui` API changes.

### CODE REVIEW

**Comment by sumwale** [comment]
crossterm should also be updated to 0.18.x?

**Comment by alexmaco** [comment]
tui 0.12.0 still uses crossterm 0.17.5. Bumping to 0.18 before tui depends on it is not very useful I think.

**Comment by sumwale** [comment]
Oh, I saw only the master branch which has a dependency on 0.18.0 and not the release.

**Comment by bvaisvil** [comment]
Thanks for this PR, looks great.

I noticed one issue though -

Screen Shot 2020-10-05 at 4 38 00 PM
 
Screen Shot 2020-10-05 at 4 39 44 PM

Looks like the number padding isn't working the same as before?

**Comment by bvaisvil** [comment]
Great, this works as expected now.

**Pull request merged**
