### PR TITLE
Support for deb package build

### PR DESCRIPTION
**Pull request by sumwale**
Initially was playing around with creating a flatpak package but discovered that its sandboxed environment does not allow access to main /proc. The sandbox /proc only lists the flatpak processes, and the filesystems are also virtual ones of the sandbox so dropped the idea. This PR adds deb package creation which will work on a large number of systems. No RPM since I don't use them and it has been a very long time I had last taken a look at RPM spec files. I can also host a PPA on Ubuntu launchpad if required.

- Added debian directory with required build files, as also desktop and icon files to launch it from standard menus. A Makefile at the top encapsulates the various build actions.

- The icon file is a generic one taken from [pngkey](https://www.pngkey.com/detail/u2t4u2a9r5a9w7u2_apps-utilities-system-monitor-icon-image-neon/) which is royalty and attribution free. It has been compressed from its initial size.

- Makefile build creates both the normal build and an NVIDIA enabled one. A wrapper shell script then chooses the appropriate binary depending on whether NVIDIA device and library is present.

- Removed build-linux-static.sh which is now covered in "make linux-static". Like above, the new target creates two binaries, and then tarball containing the two with the wrapper script is created by the target (as also the sha256 file).

### CODE REVIEW

**Comment by bvaisvil** [comment]
Thanks a lot for this! I'm not familiar with making deb packages so this is great. I'll review as soon as I can.

**Comment by sumwale** [comment]
Please also take a look at PR #67

**Comment by sumwale** [comment]
> Thanks a lot for this! I'm not familiar with making deb packages so this is great. I'll review as soon as I can.

The debian files are pretty basic and nothing much. The main one to be reviewed is the Makefile. It creates NVIDIA enabled and disabled binaries with a wrapper script selecting the appropriate one -- this needs to be checked. Please also see if the location of the three new files (icon, desktop and wrapper) in "assets" is as per your conventions.

**Comment by sumwale** [comment]
Also provide your comments about the process name. With these changes, the process name appears as either zenith.base or zenith.nvidia. This looks fine to me as it also clarifies the build being run. But if it bothers you, the script can be changed to use bash instead with "exec -a zenith ..." to change the name of process to zenith for both zenith.base/zenith.nvidia.

**Comment by sumwale** [comment]
Ok, I have changed the location of binaries to be /usr/lib/zenith/base/zenith and /usr/lib/zenith/nvidia/zenith so that the process name appears as "zenith" even in monitoring tools like top ("exec -a" does not change the name in top but only in ps). If user chooses to see the full path then base/nvidia will be visible which should be better I think.

**Comment by sumwale** [comment]
As of now, the Makefile does not have support for MacOS. Specifically the `install` target uses Linux default paths and the icon/desktop files follow Linux conventions. If you want to add MacOS support or build dmg from within Makefile then please update it as you see fit since I don't own a Mac.

**Comment by bvaisvil** [comment]
This is really great and thank you for working on this.

> Ok, I have changed the location of binaries to be /usr/lib/zenith/base/zenith and /usr/lib/zenith/nvidia/zenith so that the process name appears as "zenith" even in monitoring tools like top ("exec -a" does not change the name in top but only in ps). If user chooses to see the full path then base/nvidia will be visible which should be better I think.

This seems like a fine solution to me.

I tried out the `make && make install` this worked both on Ubuntu 18.04 and Fedora 29. Doesn't quite work on MacOS since its version of `install` doesn't have a `-D` option.

However, `make linux-static` didn't work on ubuntu. I usually did the static builds on my mac, cross compiling for linux. There the musl-gcc is called `x86_64-linux-musl-gcc` - which is what I have in the `.cargo/config` and in `build-linux-static.sh`. However, on ubuntu it is `musl-gcc`. On Ubuntu, to get the static build to work one needs to `sudo apt-get install musl-tools` then change the `Makefile` references from `x86_64-linux-musl-gcc`  to `musl-gcc`, change the reference to `x86_64-linux-musl-gcc` in the `.cargo/config` to `musl-gcc`. After those done the build finishes, the zenith binary is in `target/x86_64-unknown-linux-musl/release/zenith` as opposed to `target/release/zenith`

**Comment by sumwale** [comment]
I figured that the script must be for cross-compilation on MacOS so was unable to test the linux-static target. If you intend to do the builds on Ubuntu/Fedora in a VM instead, then I can fix the target accordingly. Otherwise I will fix the paths as you mention and you can then test it out.

About install on MacOS, it's broken in more ways like the desktop/icon files. I will need to read up on MacOS install conventions (does it still use appdirs?) and adapt the Makefile, but I don't have a way to test it currently so you will need to do it. I did find ways to run MacOS in VM but also read elsewhere that one can legally only run it on Mac hardware (probably ok for personal use?). Let me know if you would prefer to get the install target working for Mac as part of this PR, then I will try to get MacOS running in a VM.

**Comment by bvaisvil** [comment]
> I figured that the script must be for cross-compilation on MacOS so was unable to test the linux-static target. If you intend to do the builds on Ubuntu/Fedora in a VM instead, then I can fix the target accordingly. Otherwise I will fix the paths as you mention and you can then test it out.

I've been doing the binary builds manually on MacOS, but that is by no means a requirement going forward. In fact, I'm quite fine with doing the builds on linux. In that case, we would want to add a cross compilation target for MacOS, I think. That way we could just automate the building of the binary distributions in the future.

> 
> About install on MacOS, it's broken in more ways like the desktop/icon files. I will need to read up on MacOS install conventions (does it still use appdirs?) and adapt the Makefile, but I don't have a way to test it currently so you will need to do it. 

That's fine, I have no problem testing it. When I install terminal applications, I usually just install to `/usr/local/bin`. I don't think the icon files in that case are necessary.  However, I'm not at all sure that is a good convention or not as I am also not a Mac desktop developer.

> I did find ways to run MacOS in VM but also read elsewhere that one can legally only run it on Mac hardware (probably ok for personal use?).

I am also unclear of the legality of it.

> Let me know if you would prefer to get the install target working for Mac as part of this PR, then I will try to get MacOS running in a VM.

If you're amenable, I propose we do the following:

- For MacOS, I think it is sufficient to have it install to `/usr/local/bin` and forego the icons for now, unless you have a strong opinion to do something else.
- Change `linux-static` build to function on `linux`

I can add my own commits to add cross compilation target for MacOS, or if you'd like to add it to this PR, that's fine too.

**Comment by sumwale** [comment]
@bvaisvil I have updated as per above comments and more. Also added build sections in README.md including building with NVIDIA support inside a VM (where no NVIDIA GPU will be detected). Please check.

**Comment by bvaisvil** [comment]
The debian package build works great.

- `make linux-static` fails (see below). I don't usually make static builds with nvidia support, which is the library it was unable to link. We could just remove the nvidia support/check for this build option?

```
error: linking with `musl-gcc` failed: exit code: 1
  |
  = note: "musl-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-nostartfiles" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crt1.o" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crti.o" "-L" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib" "-L" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.0.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.1.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.10.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.11.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.12.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.13.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.14.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.15.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.2.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.3.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.4.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.5.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.6.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.7.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.8.rcgu.o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.zenith.3nkkohb8-cgu.9.rcgu.o" "-o" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/zenith-f12067e0e592cbc5.382kyhx3pw9trdp1.rcgu.o" "-Wl,--gc-sections" "-static" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps" "-L" "/home/benjamin/zenith/target/release/deps" "-L" "/usr/lib/nvidia" "-L" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libenv_logger-5c272bd3ab8f4d6d.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libdirs-ff4e1ca778b7cadd.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libdirs_sys-e5fad093c1a43738.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libbincode-3977ce544e012d7f.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libbyteorder-aeaee62708f270f7.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libserde-272ebb38cf13cf4e.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libgumdrop-ccd224b59637b513.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libtui-6a1e04fadb7d0b04.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcassowary-c295b92204ad5d76.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libunicode_width-5c777204eed2a395.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libunicode_segmentation-621cb59d5c37dd13.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcrossterm-c572c476476ae4c2.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libsignal_hook-8473b6a95b5b4507.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libsignal_hook_registry-78dc24cf8fb964b9.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libarc_swap-29ae977b99363879.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libmio-ea7640af7a5a7ec8.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libiovec-f263efc83e2803ec.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnet2-9e78859ecc6d608f.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libparking_lot-7c648ae7102547ee.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libparking_lot_core-88d3e8d35514e403.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libsmallvec-47b6405d8cc9d4f6.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/liblock_api-602363a875a26595.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libchrono-daa8760cda912f3f.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libtime-6ffa842b0184149b.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libbyte_unit-a609ed5d03177c27.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libbattery-9a17c50f69be04c1.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/liblazycell-05d45b034de35517.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libuom-78c6de72ea3cb94a.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libusers-36bb127cb162e4b3.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libsysinfo-9dcd694a4e801661.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libdoc_comment-d1227a7d2b16fef4.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/librayon-52108cbfa82e15fa.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/librayon_core-5cbed93c008e27cc.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnum_cpus-ac3760cfeaee1c61.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libeither-9c102d986895d786.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim-447c77affb27b646.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_sensors-04a3e4c4b5b3b2f4.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_virt-51a6d4af4f4c9153.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libraw_cpuid-4ef64ce7e537edda.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_process-6c4f1284f5247bdf.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libordered_float-75a9c9b227b7d884.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_net-4a56f0ffa6074e9c.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libmacaddr-19034ec0d18ea407.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_memory-17b9a30e05dda35b.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_host-0605175c5fd421b0.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libplatforms-8b6722190ebef976.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_disk-fc2c4df821df95dd.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_cpu-cc4ff373ba37fed0.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libglob-a268736dc3275d2f.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_runtime-0f8938cf2164d963.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libsmol-cd1462991b7903d5.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libpiper-6e237fc1095c7ab8.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libasync_task-ecd1b10fb63e4b36.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libscoped_tls_hkt-7969765b05485b92.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcrossbeam-dfdd2c0a1265fbb8.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcrossbeam_queue-09e14f1291d79be0.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcrossbeam_channel-22ea83540db46980.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcrossbeam_deque-670cc712d7adaf62.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcrossbeam_epoch-3609b7d4ce95a487.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libscopeguard-ffbd760586b8b65a.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libmemoffset-7d0ecc796515682f.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcrossbeam_utils-8155c05114e3710a.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libmaybe_uninit-344bb65842a9f8e9.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libsocket2-28038e5ef70fb182.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_timer-bccf1e6b0e1608e7.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libheim_common-0642812de5184b0f.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnix-439e28a5a5ef70dc.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libvoid-cb0dfe4f6efd4204.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/liblazy_static-a48fe5e6b61afd76.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libuom-bfefb5417bfe522e.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libtypenum-9fbb58c2f52dd650.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnum_rational-b7483ed7b0affc55.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnum_integer-7dc670a0e24b2bd8.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnum_traits-3241927bd2087e1e.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures-209a64f4d9ea65ba.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_executor-4c9164ff6a2db85c.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_util-0d07d7fc3042a60d.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libmemchr-49e9e1263a62805a.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libproc_macro_nested-756b7db89364b2a2.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_io-edc3b5a180ace723.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libslab-e7d53a954763d1dd.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_channel-e2376280357cc55b.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libpin_project-615d64711084b118.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_sink-9ad4579909a900c5.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_task-0ace70794e5f09b5.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libonce_cell-91707f2b2f7c316d.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libpin_utils-2490fb42224c8fe5.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libfutures_core-ad3fec7c4eaa2b02.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnvml_wrapper-15b23bd75649d9fc.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libnvml_wrapper_sys-7e301a4041de2fc5.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libbitflags-e97ee11dba73156b.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/liberror_chain-2c5b2620a84f1521.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libbacktrace-927f2075669d57a2.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libobject-961b14d956a0c2a0.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/liblibc-ecf88da6a3e46d6a.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libaddr2line-5836902f3c0c9bb4.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libgimli-c752d6f7264447c3.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/librustc_demangle-c6a94cc3b2c5029f.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/liblog-af329892ab56dbd7.rlib" "/home/benjamin/zenith/target/x86_64-unknown-linux-musl/release/deps/libcfg_if-f89be652aaabc0c0.rlib" "-Wl,--start-group" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-01068eff9ed27231.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-7208584e75d18448.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-b2e168575bfa6ad2.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-b2d08051a939761b.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace-758ecd4f3d0d5f27.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace_sys-ffe54e149ef6ebdf.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-16144a86eadb4f35.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libunwind-6b148baeeff3cbd8.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-93fe1220749bacfa.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-4a2784206852a82d.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-f64656466e752b3a.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-fb744cd51ebaca4a.rlib" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-bcd4932faca443ea.rlib" "-Wl,--end-group" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-c97728121c289b8f.rlib" "-Wl,-Bdynamic" "-lnvidia-ml" "-s" "/home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/crtn.o"
  = note: /usr/bin/ld: cannot find -lnvidia-ml
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `zenith`.

To learn more, run the command again with --verbose.
install: cannot stat 'target/x86_64-unknown-linux-musl/release/zenith': No such file or directory
Makefile:16: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by sumwale** [comment]
It works in my older Xubuntu 16.04 VM but doesn't work in latest one. Perhaps newer musl-gcc needs static libnvidia-ml library (which would be the right thing to do) while the driver seems to ship only with dynamic libraries. I have added a BUILD_NVIDIA flag to Makefile that can disable it: `make linux-static BUILD_NVIDIA=false`

**Comment by sumwale** [comment]
I have updated the Makefile to have BUILD_NVIDIA=false for linux-static by default. The zenith.nvidia executable being created in the Xubuntu 16.04 VM is actually a dynamically linked one, so musl-gcc is working incorrectly there.

**Comment by bvaisvil** [comment]
From my tests this appears to be working well. There is still an issue where the `make` on MacOS executes a few commands that will fail or are not needed.

For example when running the `make`:
```bash
mkdir -p build/dynamic
rm -f build/dynamic/zenith.base
install -m 755 target/release/zenith build/dynamic/zenith.base
assets/zenith-libnvidia-detect.sh: line 6: ldconfig: command not found
```

Since nvidia support won't work on Mac, we don't need to run the detect script in that case.

And for `make install`:
```bash
mkdir -p "/usr/local/bin" "/usr/local/share/applications" "/usr/local/share/pixmaps"
install -m 644 assets/zenith.png "/usr/local/share/pixmaps/zenith.png"
install -m 644 assets/zenith.desktop "/usr/local/share/applications/zenith.desktop"
```

The image installs here are not necessary. Could you add an `if $OSTYPE == "darwin"*` on those commands?

After that I think we're done and we can merge?

**Comment by sumwale** [comment]
> From my tests this appears to be working well. There is still an issue where the `make` on MacOS executes a few commands that will fail or are not needed.

Done. Please merge if there are no further comments.

**Comment by sumwale** [comment]
> From my tests this appears to be working well. There is still an issue where the `make` on MacOS executes a few commands that will fail or are not needed.

Done. Please merge if there are no further comments.

**Comment by bvaisvil** [comment]
Test and this works great. Thank you _very_ much for all the work and your patience with the process!

**Pull request merged**
