### PR TITLE
Fix disk refresh and temperature display

### PR DESCRIPTION
**Pull request by alexmaco**

### CODE REVIEW

**Comment by bvaisvil** [comment]
Thank you a lot for this PR. I did notice one issue. The free space percentage of the disk display isn't right now. (Please see screenshot).
Screen Shot 2021-03-23 at 11 52 52 AM

If you could fix that issue I'd be happy to merge!

**Comment by alexmaco** [comment]
Sadly I'm not seeing the issue on any of my machines, but I'm only running linux. If you're testing it on a mac, i would guess it's a sysinfo issue. What I can do is change the disk fetching to use `heim`. Does that sound ok?

**Comment by bvaisvil** [comment]
Yes, I ran that test on a Mac. I ran another test on centos and I did not see the issue.

Let me try to find out where in `sysinfo` this is happening. I did a quick search of the current and past issues there and I didn't see someone bring this up.

**Comment by bvaisvil** [comment]
Okay, I  committed a fix to my fork of `sysinfo` and that corrects the issue. So I'll merge these commits. Thanks again for this PR!

**Pull request merged**
