### PR TITLE
Added Debian/Ubuntu package instructions to README

### PR DESCRIPTION
**Pull request by sumwale**
Uploaded the deb package on [bintray](https://bintray.com/sumwale/debian/zenith) and added instructions to README

### CODE REVIEW

**Comment by bvaisvil** [comment]
Thank you for this!!

 However, I think I'd prefer to have this hosted under my name. I've created an account at bintray to facilitate this. After I've got it setup, could you change the links to refer to my bintray?

**Comment by sumwale** [comment]
Sure, add a comment when the package is uploaded.

I had built the deb in a Ubuntu 16.04 VM with NVIDIA support as noted in README (install nvidia driver but disable it with prime-select, then set LD_LIBRARY_PATH in debuild -e). Then I had also tested it in MX-Linux 18.3 VM (Debian 9 compatible). I think for now just upload the [deb](https://bintray.com/sumwale/debian/download_file?file_path=pool%2Fz%2Fzenith%2Fzenith_0.10.1-1_amd64.deb) to your account and setup the properties. Let me know for future releases if you do not have the required setup I can do the build, test it and pass it over.

**Comment by bvaisvil** [comment]
Sorry for the delay! My plan is to do the 0.11.0 release, then I'll add that `.deb` to bintray and we can update the readme with that information.

**Comment by sumwale** [comment]
Closing this. Will re-open once updated deb packages are uploaded.

**Comment by sumwale** [comment]
@bvaisvil I have separated out the Arch linux instructions and debian/changelog version change to a separate PR #81 so that one can be merged immediately.

**Comment by bvaisvil** [comment]
I've uploaded to bintray: https://bintray.com/bvaisvil/debian/zenith/0.11.0

Hopefully, I've done this correctly, let me know.

**Comment by sumwale** [comment]
@bvaisvil Have you uploaded any deb package yet? I cannot see anything under Files tab. Compare [yours](https://bintray.com/bvaisvil/debian/zenith/0.11.0) to [this](https://bintray.com/sumwale/debian/zenith/0.10.1).

To start, you will need to create a "New version" under the Versions section here: https://bintray.com/bvaisvil/debian/zenith. It will also be good to Edit that page and add License as MIT and Maturity as stable. Check https://bintray.com/sumwale/debian/zenith for reference. I think the github project will also need to add the 0.11.0 tag so that everything works as expected.

Then click on the 0.11.0 version page and you can select Upload Files to publish your deb package. When you upload a deb package, you will be asked the distribution, architecture and component that I used as "stable", "amd64" and "main" respectively. Somewhere you will also be asked whether to sign it with bintray's standard key or you can generate your own personal key and sign with it -- I had chosen the former to keep things simpler (perhaps this was asked during debian repository creation). You only need to upload an unsigned package generated with "debuild -us -uc ..." when choosing to use bintray's key. Notice how there is also a "Debian Details" section on the page (https://bintray.com/sumwale/debian/zenith/0.10.1) that shows the chosen architecture (amd64), component (main) and distribution (stable) during the upload.

When creating a debian repository you should have chosen the recommended standard repository layout, then the Files tab should show similar layout to here: https://bintray.com/sumwale/debian/zenith/0.10.1#files. I had also chosen the "Github file" option in the Readme tab so that Readme tab shows the same content as the github project page.

**Comment by bvaisvil** [comment]
I had forgot to publish, but now that I have I see that my paths are incorrect. I'll correct them and re-upload & publish. I'll let you know when it is done. Thank you for your assistance!

**Comment by bvaisvil** [comment]
Okay, I think it is setup right now. Could you check and let me know? Thanks!

**Comment by sumwale** [comment]
@bvaisvil Repository looks good but the deb package seems to be built on Ubuntu 20.04 (depends on libgcc-s1) and will not install on lower versions. I have built a new deb on Ubuntu 16.04 and tested working on both Ubuntu >= 16.04 and Debian >= 9 here: https://bintray.com/sumwale/debian/download_file?file_path=pool%2Fz%2Fzenith%2Fzenith_0.11.0-1_amd64.deb

You can download this one, then delete the deb and deb.asc files in your repository (https://bintray.com/bvaisvil/debian/zenith navigate to Files -> pool/z/zenith), wait a few minutes for repository to update itself, then upload this deb.

**Comment by bvaisvil** [comment]
Okay, I updated the `.deb`

**Comment by sumwale** [comment]
Tested the new one and works perfectly on Ubuntu/Debian. README has been updated. Thanks.

**Comment by bvaisvil** [comment]
Is there anything left to do or are we okay to merge?

**Comment by sumwale** [comment]
Ok to merge.

**Pull request merged**
